# Generated by Django 4.0.3 on 2022-07-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_picturename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pictureName',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
