# Generated by Django 4.0.3 on 2022-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkType',
            field=models.CharField(default='E', max_length=1),
            preserve_default=False,
        ),
    ]
