# Generated by Django 4.0.3 on 2022-07-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_linktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(max_length=100),
        ),
    ]
